### ISSUE TITLE
test command not working on windows

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/svelte-windicss-preprocess#21]
```sh
❯ pnpm run test

> svelte-windicss-preprocess@2.1.4 test C:\Users\Alexander\Documents\projects\windicss\svelte-windicss-preprocess
> ts-node -O '{"module":"commonjs"}' node_modules/jasmine/bin/jasmine --config=jasmine.json

undefined:1
{module:commonjs}
 ^

SyntaxError: Unexpected token m in JSON at position 1
    at JSON.parse (<anonymous>)
    at parse (C:\Users\Alexander\Documents\projects\windicss\svelte-windicss-preprocess\node_modules\.pnpm\ts-node@9.1.1_typescript@4.1.5\node_modules\ts-node\dist\index.js:130:45)
    at arg (C:\Users\Alexander\Documents\projects\windicss\svelte-windicss-preprocess\node_modules\.pnpm\arg@4.1.3\node_modules\arg\index.js:122:24)
    at main (C:\Users\Alexander\Documents\projects\windicss\svelte-windicss-preprocess\node_modules\.pnpm\ts-node@9.1.1_typescript@4.1.5\node_modules\ts-node\dist\bin.js:15:67)
    at Object.<anonymous> (C:\Users\Alexander\Documents\projects\windicss\svelte-windicss-preprocess\node_modules\.pnpm\ts-node@9.1.1_typescript@4.1.5\node_modules\ts-node\dist\bin.js:238:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
 ERROR  Test failed. See above for more details.
```

**Comment by voorjaar** [comment]
I will switch to esno later.
