### ISSUE TITLE
Duplicate `windi:inject` attribute error while working with svelte kit component library

### ISSUE THREAD

**Issue by bhvngt** [windicss/svelte-windicss-preprocess#259]
### Describe the bug

I am currently using this plugin in a module where I am importing another svelte kit component library built using `svelte-kit package` command. I get following error when building my app.

```
3:05:11 PM [vite] Error when evaluating SSR module /@fs/Volumes/Demo/libs/ui/package/index.js:
ParseError: Attributes need to be unique
    at error (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17698:19)
    at Parser$1.error (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17774:9)
    at check_unique (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:16927:20)
    at read_attribute (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17031:5)
    at tag (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:16838:25)
    at new Parser$1 (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17733:21)
    at parse$3 (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17865:20)
    at compile (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:31310:17)
    at compileSvelte (file:///Volumes/Demo/common/temp/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.24_svelte@3.43.0+vite@2.5.10/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:318:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
3:05:11 PM [vite] Error when evaluating SSR module /src/routes/index.svelte:
ParseError: Attributes need to be unique
    at error (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17698:19)
    at Parser$1.error (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17774:9)
    at check_unique (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:16927:20)
    at read_attribute (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17031:5)
    at tag (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:16838:25)
    at new Parser$1 (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17733:21)
    at parse$3 (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17865:20)
    at compile (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:31310:17)
    at compileSvelte (file:///Volumes/Demo/common/temp/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.24_svelte@3.43.0+vite@2.5.10/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:318:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Attributes need to be unique
59: {/if}
60: 
61: <style windi:inject windi:inject lang="postcss" global>:global(.navbar) {
                        ^
62:   display: flex;
63:   align-items: center;
ParseError: Attributes need to be unique
    at error (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17698:19)
    at Parser$1.error (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17774:9)
    at check_unique (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:16927:20)
    at read_attribute (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17031:5)
    at tag (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:16838:25)
    at new Parser$1 (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17733:21)
    at parse$3 (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:17865:20)
    at compile (file:///Volumes/Demo/common/temp/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:31310:17)
    at compileSvelte (file:///Volumes/Demo/common/temp/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.24_svelte@3.43.0+vite@2.5.10/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:318:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It works if I patch this package with `tmpContent = tmpContent.replace("windi:inject","");` before this [line](https://github.com/windicss/svelte-windicss-preprocess/blob/64a03e05b542d3825d45afe0a4b7b06f8046666f/src/utils.ts#L83). Let me know, if you would like me to raise a PR. 

Thank you very much for building and sharing this package.

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 232.80 MB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.9.1 - /var/folders/n0/qyzlydqj6cv8qt68qd6dbprh0000gn/T/fnm_multishells/14505_1632574516534/bin/node
    Yarn: 1.22.11 - /var/folders/n0/qyzlydqj6cv8qt68qd6dbprh0000gn/T/fnm_multishells/14505_1632574516534/bin/yarn
    npm: 7.21.1 - /var/folders/n0/qyzlydqj6cv8qt68qd6dbprh0000gn/T/fnm_multishells/14505_1632574516534/bin/npm
  IDEs:
    IntelliJ: 2021.2.2
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.60.1 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Browsers:
    Chrome: 93.0.4577.82
    Chrome Canary: 96.0.4653.2
    Edge: 94.0.992.31
    Firefox: 86.0.1
    Safari: 15.0
  npmPackages:
    svelte: ^3.43.0 => 3.43.0 
    svelte-windicss-preprocess: ^4.0.12 => 4.0.12 
    windicss: ^3.1.7 => 3.1.7
```

### Used Package Manager

pnpm

**Comment by bhvngt** [comment]
Thanks @alexanderniebuhr for your approval. Do you plan to release this in the near future?

**Comment by alexanderniebuhr** [comment]
It actually lands in `4.1.0-beta.3`
`4.1.0` seems to be pretty stable so far.. not quite ready to release it to stable yet.

**Comment by bhvngt** [comment]
That too will work for me. Will switch over to 4.1.0-beta.*. Thanks a ton for the merge.
