### ISSUE TITLE
Rollup unhappy with WindiCSS config

### ISSUE THREAD

**Issue by Grymse** [windicss/svelte-windicss-preprocess#306]
### Describe the bug

Following the tutorial about installing the WindiCSS preprocessor for regular Svelte on your website gives me this error during compilation. This applies to all machines I've tried it on. On both new and old projects. It seems that either some Rollup update or may update here has broken the default installation. I have tried reaching out on Discord, but I figured it would be more appropriate to add the issue here.

The error message here is on Windows 11, node v. 14.14.0

I got the same message on a Macbook Pro 2018, node v. 17.xx.xx

### System Info

```shell
Error: While loading the Rollup configuration from "rollup.config.js", Node tried to require an ES module from a CommonJS file, which is not supported. A common cause is if there is a package.json file with "type": "module" in the same folder. You can try to fix this by changing the extension of your configuration file to ".cjs" or ".mjs" depending on the content, which will prevent Rollup from trying to preprocess the file but rather hand it to Node directly.
    at Object.error (C:\Users\PROni\Documents\Uni\Dist\dist-chat\Assignment\ui\node_modules\rollup\dist\shared\rollup.js:158:30)
    at loadConfigFromBundledFile (C:\Users\PROni\Documents\Uni\Dist\dist-chat\Assignment\ui\node_modules\rollup\dist\shared\loadConfigFile.js:563:27)
    at getDefaultFromTranspiledConfigFile (C:\Users\PROni\Documents\Uni\Dist\dist-chat\Assignment\ui\node_modules\rollup\dist\shared\loadConfigFile.js:541:12)
    at loadConfigFile (C:\Users\PROni\Documents\Uni\Dist\dist-chat\Assignment\ui\node_modules\rollup\dist\shared\loadConfigFile.js:500:11)
    at Object.loadAndParseConfigFile (C:\Users\PROni\Documents\Uni\Dist\dist-chat\Assignment\ui\node_modules\rollup\dist\shared\loadConfigFile.js:481:21)
    at reloadConfigFile (C:\Users\PROni\Documents\Uni\Dist\dist-chat\Assignment\ui\node_modules\rollup\dist\shared\watch-cli.js:365:51)
    at loadConfigFromFileAndTrack (C:\Users\PROni\Documents\Uni\Dist\dist-chat\Assignment\ui\node_modules\rollup\dist\shared\watch-cli.js:349:9)
    at watch (C:\Users\PROni\Documents\Uni\Dist\dist-chat\Assignment\ui\node_modules\rollup\dist\shared\watch-cli.js:386:9)
```

### Used Package Manager

npm

**Comment by alexanderniebuhr** [comment]
please share a minimal repro

**Comment by Grymse** [comment]
Hi. Thanks for the reply!

I wouldnt have to share a repo. This error comes up independent of project.
Running the following commands on any pc gives me the error

npx degit sveltejs/template my-app
cd my-app
npm i
npm i -D svelte-windicss-preprocess

Running now works fine.

But adding the required lines in rollup.config.js

import { windi } from 'svelte-windicss-preprocess';

and

preprocess: [windi({}),],

In the svelte object as specified in the tutorial found in your tutorial
https://windicss.org/integrations/svelte.html

As soon as the preprocessor is added it breaks with the error shown in the
issue. In an old project I accidentally ran “npm i”, which then broke that
project as well. I had another project where I simply took the node_modules
folder from, which made everything work again

If you still want a repo, I’ll send it over tomorrow

Kind regards,
Nicolai Grymer




lør. 6. nov. 2021 kl. 21.15 skrev Alexander Niebuhr <
***@***.***>:

**Comment by Grymse** [comment]
https://github.com/Grymse/svelte-windicss-bug/

**Comment by alexanderniebuhr** [comment]
I'll check and see if I find the issue

**Comment by alexanderniebuhr** [comment]
@Grymse use v4.1.6-beta.2 please. will be available in next stable update soon.
```sh
npm install svelte-windicss-preprocess@next
```
