### ISSUE TITLE
Snowpack example broken

### ISSUE THREAD

**Issue by trevyn** [windicss/svelte-windicss-preprocess#41]
From fresh clone of `main`:

```
eden ~/svelte-windicss-preprocess (main)> cd example/snowpack/
eden ~/s/e/snowpack (main)> pnpm install
Lockfile is up-to-date, resolution step is skipped
Packages: +42
++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/eden/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 42, reused 0, downloaded 42, added 42, done
node_modules/.pnpm/svelte-preprocess@4.6.9_svelte@3.32.3/node_modules/svelte-preprocess: Running postinstall script, done in 25ms
node_modules/.pnpm/esbuild@0.8.52/node_modules/esbuild: Running postinstall script, done in 121ms

dependencies:
+ svelte 3.32.3
+ svelte-windicss-preprocess 2.2.1

devDependencies:
+ @snowpack/plugin-svelte 3.5.2
+ rollup 2.39.1
+ snowpack 3.0.13
+ svelte-hmr 0.12.6
eden ~/s/e/snowpack (main)> pnpm run dev

> @ dev /Users/eden/svelte-windicss-preprocess/example/snowpack
> snowpack dev --open none

[snowpack] Error: Cannot find module '../../dist/index.js'
Require stack:
- /Users/eden/svelte-windicss-preprocess/example/snowpack/svelte.config.js
- /Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/@snowpack/plugin-svelte@3.5.2_rollup@2.39.1+svelte@3.32.3/node_modules/@snowpack/plugin-svelte/plugin.js
- /Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/snowpack@3.0.13/node_modules/snowpack/lib/index.js
- /Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/snowpack@3.0.13/node_modules/snowpack/index.bin.js

Error: Cannot find module '../../dist/index.js'
Require stack:
- /Users/eden/svelte-windicss-preprocess/example/snowpack/svelte.config.js
- /Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/@snowpack/plugin-svelte@3.5.2_rollup@2.39.1+svelte@3.32.3/node_modules/@snowpack/plugin-svelte/plugin.js
- /Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/snowpack@3.0.13/node_modules/snowpack/lib/index.js
- /Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/snowpack@3.0.13/node_modules/snowpack/index.bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/eden/svelte-windicss-preprocess/example/snowpack/svelte.config.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at plugin (/Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/@snowpack/plugin-svelte@3.5.2_rollup@2.39.1+svelte@3.32.3/node_modules/@snowpack/plugin-svelte/plugin.js:71:30)
    at execPluginFactory (/Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/snowpack@3.0.13/node_modules/snowpack/lib/index.js:71552:18)
    at loadPluginFromConfig (/Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/snowpack@3.0.13/node_modules/snowpack/lib/index.js:71565:22)
    at /Users/eden/svelte-windicss-preprocess/example/snowpack/node_modules/.pnpm/snowpack@3.0.13/node_modules/snowpack/lib/index.js:71589:24
    at Array.forEach (<anonymous>)

 ERROR  Command failed with exit code 1.
```

**Comment by alexanderniebuhr** [comment]
`pnpm run dev || pnpm run build` in root folder before starting

**Comment by trevyn** [comment]
Thanks!:)
