### ISSUE TITLE
Couldn't resolve parser "svelte"

### ISSUE THREAD

**Issue by cgibsonmm** [windicss/svelte-windicss-preprocess#62]
After following the guide using webpack with sapper(on electron) I am getting this error message!

```Shell
src/node_modules/@sapper/internal/App.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: Couldn't resolve parser "svelte"
    at new Promise (<anonymous>)
webpack:///./src/routes/index.svelte?:1
throw new Error("Module build failed (from ./node_modules/svelte-loader/index.js):\nError: Couldn't resolve parser \"svelte\"\n    at resolveParser (/Users/corey/freelance/daily/node_modules/prettier/index.js:13599:13)\n    at normalize$1 (/Users/corey/freelance/daily/node_modules/prettier/index.js:13695:18)\n    at format (/Users/corey/freelance/daily/node_modules/prettier/index.js:15111:46)\n    at /Users/corey/freelance/daily/node_modules/prettier/index.js:57542:12\n    at format (/Users/corey/freelance/daily/node_modules/prettier/index.js:57562:12)\n    at _preprocess (/Users/corey/freelance/daily/node_modules/svelte-windicss-preprocess/index.js:199:23)\n    at /Users/corey/freelance/daily/node_modules/svelte-windicss-preprocess/index.js:420:27\n    at new Promise (<anonymous>)\n    at markup (/Users/corey/freelance/daily/node_modules/svelte-windicss-preprocess/index.js:418:20)\n    at preprocess (/Users/corey/freelance/daily/node_modules/svelte/compiler.js:26987:34)");
^

Error: Module build failed (from ./node_modules/svelte-loader/index.js):
Error: Couldn't resolve parser "svelte"
    at resolveParser (/Users/corey/freelance/daily/node_modules/prettier/index.js:13599:13)
    at normalize$1 (/Users/corey/freelance/daily/node_modules/prettier/index.js:13695:18)
    at format (/Users/corey/freelance/daily/node_modules/prettier/index.js:15111:46)
    at /Users/corey/freelance/daily/node_modules/prettier/index.js:57542:12
    at format (/Users/corey/freelance/daily/node_modules/prettier/index.js:57562:12)
    at _preprocess (/Users/corey/freelance/daily/node_modules/svelte-windicss-preprocess/index.js:199:23)
    at /Users/corey/freelance/daily/node_modules/svelte-windicss-preprocess/index.js:420:27
    at new Promise (<anonymous>)
    at markup (/Users/corey/freelance/daily/node_modules/svelte-windicss-preprocess/index.js:418:20)
    at preprocess (/Users/corey/freelance/daily/node_modules/svelte/compiler.js:26987:34)
    at eval (webpack:///./src/routes/index.svelte?:1:7)
    at Object../src/routes/index.svelte (/Users/corey/freelance/daily/__sapper__/dev/server/server.js:564:1)
    at __webpack_require__ (/Users/corey/freelance/daily/__sapper__/dev/server/server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/internal/manifest-server.mjs?:8:78)
    at Module../src/node_modules/@sapper/internal/manifest-server.mjs (/Users/corey/freelance/daily/__sapper__/dev/server/server.js:450:1)
    at __webpack_require__ (/Users/corey/freelance/daily/__sapper__/dev/server/server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/server.mjs?:7:83)
    at Module../src/node_modules/@sapper/server.mjs (/Users/corey/freelance/daily/__sapper__/dev/server/server.js:462:1)
    at __webpack_require__ (/Users/corey/freelance/daily/__sapper__/dev/server/server.js:21:30)
    at eval (webpack:///./src/server.js?:6:72)
```

Any ideas would be great!

**Comment by alexanderniebuhr** [comment]
do you have svelte installed as dependency?

**Comment by cgibsonmm** [comment]
I have it in my dev dependencies yes!

**Comment by alexanderniebuhr** [comment]
yeah, i know the bug, i do not know a fix for now. i need to use prettier-svelte-plugin, it should be bundled but electron might be using it differently. I will add an config flag tomorrow for that.

If that is not breaking your app, you could set `process.env.BROWSER = true`, this should be a workaround

**Comment by cgibsonmm** [comment]
Thank you, I am was trying out [a create sapper electron build](https://github.com/soulehshaikh99/create-sapper-electron-app) I found to try it out. It does not seem to be maintained or supported really. Might just need to look somewhere else.

**Comment by alexanderniebuhr** [comment]
well, the issue with the missing lib is definitely a bug. It will be fixed, v2 should not have that problem. v3 is still beta

**Comment by cgibsonmm** [comment]
Okay, thanks for the info. here is the link to my project with the error if you wanted to have a look. I think you are already aware of the problem though so. [daily](https://github.com/cgibsonmm/daily/tree/taiwind)

**Comment by OysterD3** [comment]
I had this issue in rollup as well. `rollup-plugin-node-resolve` suppose to use `browser`
```js
// ...
plugins: [
  resolve({
    browser: true,
  }),
]
```

But `svelte-windicss-preprocess` still point to `main`, I had to do this
```js
import windicssPreprocess from "svelte-windicss-preprocess/browser";
```

**Comment by alexanderniebuhr** [comment]
will be fixed in beta.9 later today

**Comment by cgibsonmm** [comment]
Can confirm that adding 

```js
... 
preprocess: require("svelte-windicss-preprocess/browser").preprocess(
...
```

Has fixed this
